name: Deploy to Environment - Personal

on:
  push:
    tags:
      - 'dev-*'
      - 'test-*'
      - 'prod-*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract environment from tag
        id: extract
        run: |
          TAG_NAME=${GITHUB_REF##*/}
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "environment=$(echo $TAG_NAME | cut -d'-' -f1)" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
                  lusalvi/personal:${{ steps.extract_env.outputs.tag }}
                  lusalvi/personal:${{ steps.extract_env.outputs.env }}
